---
title: "Homework 3"
author: "Austin Chan"
date: "3/24/2020"
output: html_document
---

```{r}
library(MASS)
library(caret)
library(glmnet)
```



```{r}
raw = read.csv(".//crime-training-data_modified.csv", stringsAsFactors = F)

scaled_data = data.frame(scale(raw[,!names(raw) %in% c("target","chas")]))

scaled_data$chas = raw$chas
scaled_data$target = as.factor(raw$target)
```



```{r}
hist(scaled_data$zn)

hist(scaled_data$indus)

hist(scaled_data$chas)

hist(scaled_data$nox)

hist(scaled_data$rm)

hist(scaled_data$age)

hist(scaled_data$dis)

hist(scaled_data$rad)

hist(scaled_data$tax)

hist(scaled_data$ptratio)

hist(scaled_data$lstat)

hist(scaled_data$medv)
```

```{r}
set.seed(100)

scaled_index = createDataPartition(scaled_data$target, p = 0.8, list = F)

scaled_train = scaled_data[scaled_index,]
scaled_test = scaled_data[-scaled_index,]
```


```{r}
base_model = glm(target~.,data = scaled_train, family = binomial)

summary(base_model)
```

```{r}
stepAIC_model = stepAIC(base_model, direction = "both")

summary(stepAIC_model)
```


```{r}
caret_model = train(
  form = target~.,
  data = scaled_train,
  trControl = trainControl(method = "cv", number = 5),
  method = "glm",
  family = "binomial"
)
```

```{r}
caret_model
```

```{r}
glm_net = train(
  target ~ . ^ 2, data = scaled_train,
  method = "glmnet",
  trControl = trainControl(method = "cv", number = 5),
  tuneLength = 10
)
```


```{r}
summary(stepAIC_model)

summary(caret_model)
```

```{r}
coef(glm_net$finalModel,glm_net$bestTune$lambda)
```


```{r}
caret_results = predict(caret_model, newdata = scaled_test, type = "prob")

step_aic_results = predict.glm(stepAIC_model, newdata = scaled_test, type = "response")

glm_net_results = predict(glm_net, newdata = scaled_test, type = "prob")
```

```{r}
caret_results$predictions = 0
caret_results$predictions[caret_results$`1` >= 0.5] = 1
caret_results$predictions = as.factor(caret_results$predictions)

caret_results

step_aic_results_df = data.frame(probs = step_aic_results)
step_aic_results_df$predictions = 0
step_aic_results_df$predictions[step_aic_results_df$probs >= 0.5] = 1
step_aic_results_df$predictions = as.factor(step_aic_results_df$predictions)

step_aic_results_df

glm_net_results$predictions = 0
glm_net_results$predictions[glm_net_results$`1` >= 0.5] = 1
glm_net_results$predictions = as.factor(glm_net_results$predictions)

glm_net_results
```

```{r}
caret::confusionMatrix(caret_results$predictions,scaled_test$target, positive = "1")
```

```{r}
caret::confusionMatrix(step_aic_results_df$predictions,scaled_test$target, positive = "1")
```

```{r}
caret::confusionMatrix(glm_net_results$predictions,scaled_test$target, positive = "1")
```




******Jose's Model******
```{r}
library(caret) #Marchine and glm library
library(magrittr)
library(e1071)
library(pROC)
```

```{r}
t_data <- "https://raw.githubusercontent.com/JMawyin/MSDS2020-621/master/crime-training-data_modified.csv"
e_data <- "https://raw.githubusercontent.com/JMawyin/MSDS2020-621/master/crime-evaluation-data_modified.csv"

HW3_training <- read.csv(t_data, header = TRUE)
HW3_evaluation <- read.csv(e_data, header = TRUE)
```

```{r}
head(raw)
HW3_training <- raw
```

```{r}
outcomeName <- 'target'
predictorsNames <- names(HW3_training)[names(HW3_training) != outcomeName]
predictorsNames
```

```{r}
HW3_training$target2 <- ifelse(HW3_training$target==1,'yes','nope')
table(HW3_training$target2)
HW3_training$target2 <- as.factor(HW3_training$target2)
table(HW3_training$target2)
outcomeName <- 'target2'
outcomeName
```

```{r}
outcomeName <- 'target2'
HW3_training$target <- as.numeric(HW3_training$target)
set.seed(1234)
splitIndex <- createDataPartition(HW3_training[,outcomeName], p = .75, list = FALSE, times = 1)
trainDF <- HW3_training[ splitIndex,]
testDF  <- HW3_training[-splitIndex,]
```

```{r}
head(trainDF)
head(testDF)
predictorsNames
outcomeName
```
```{r}
objControl <- trainControl(method='cv', number=3, returnResamp='none', summaryFunction = twoClassSummary, classProbs = TRUE)
```

```{r}
outcomeName <- 'target2'
objModel_Jose <- train(trainDF[,predictorsNames], trainDF[,outcomeName], 
                  method='gbm', 
                  trControl=objControl,  
                  metric = "ROC",
                  preProc = c("center", "scale"))
```

```{r}
summary(objModel_Jose)
```

```{r}
predictions_Jose <- predict(object=objModel_Jose, HW3_evaluation[,predictorsNames], type='prob')
head(predictions_Jose)
```








